//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManager.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreManagerDBEntities : DbContext
    {
        public StoreManagerDBEntities()
            : base("name=StoreManagerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriesTabel> CategoriesTabels { get; set; }
        public virtual DbSet<CustomersTabel> CustomersTabels { get; set; }
        public virtual DbSet<ProductsTabel> ProductsTabels { get; set; }
        public virtual DbSet<PurchaseBillDetailsTabel> PurchaseBillDetailsTabels { get; set; }
        public virtual DbSet<PurchaseBillTabel> PurchaseBillTabels { get; set; }
        public virtual DbSet<SalesBillDetailsTabel> SalesBillDetailsTabels { get; set; }
        public virtual DbSet<SalesBillTabel> SalesBillTabels { get; set; }
        public virtual DbSet<SuppliersTabel> SuppliersTabels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UsersTabel> UsersTabels { get; set; }
    }
}
