//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseBillDetailsTabel
    {
        public int Id { get; set; }
        public int PurchaseBill_ID { get; set; }
        public int ProductID { get; set; }
        public int Quantity { get; set; }
        public decimal CostPrice { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual ProductsTabel ProductsTabel { get; set; }
        public virtual PurchaseBillTabel PurchaseBillTabel { get; set; }
    }
}
