//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseBillTabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseBillTabel()
        {
            this.PurchaseBillDetailsTabels = new HashSet<PurchaseBillDetailsTabel>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int SupplierId { get; set; }
        public int UserId { get; set; }
        public decimal Total { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalAfterDiscount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseBillDetailsTabel> PurchaseBillDetailsTabels { get; set; }
        public virtual SuppliersTabel SuppliersTabel { get; set; }
        public virtual UsersTabel UsersTabel { get; set; }
    }
}
