//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBillTabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesBillTabel()
        {
            this.SalesBillDetailsTabels = new HashSet<SalesBillDetailsTabel>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public int UserId { get; set; }
        public decimal Total { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalAfterDiscount { get; set; }
    
        public virtual CustomersTabel CustomersTabel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesBillDetailsTabel> SalesBillDetailsTabels { get; set; }
        public virtual UsersTabel UsersTabel { get; set; }
    }
}
