//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesBillDetailsTabel
    {
        public int Id { get; set; }
        public int ProductID { get; set; }
        public int SalesBill_ID { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual ProductsTabel ProductsTabel { get; set; }
        public virtual SalesBillTabel SalesBillTabel { get; set; }
    }
}
